#!/bin/bash
cd /home/selker/eop/poverty/dry_run
# Hyperparameter search
/home/selker/.conda/envs/dry_run/bin/python main_hparam.py main --config /home/selker/eop/eop/run_togo_simulations/simulations_20260318/hparam/configs/TGO_alpha_earth_and_survey_satellite_sample/gt_continuous_gap.yaml --learnsavedir /home/selker/eop/eop/run_togo_simulations/simulations_20260318/learn/results/TGO_alpha_earth_and_survey_satellite_sample 
sleep 1
# Learning
/home/selker/.conda/envs/dry_run/bin/python main_learn.py main --config /home/selker/eop/eop/run_togo_simulations/simulations_20260318/hparam/results/TGO_alpha_earth_and_survey_satellite_sample/output_gt_continuous_gap.yaml --trainpath /data/eop/country_data/TGO/cleaned_for_nontrad_experiments/alpha_earth_and_survey_satellite_sample/train.parquet --testpath /data/eop/country_data/TGO/cleaned_for_nontrad_experiments/alpha_earth_and_survey_satellite_sample/test.parquet --summarypath /data/eop/country_data/TGO/cleaned_for_nontrad_experiments/alpha_earth_and_survey_satellite_sample/summary.parquet --device cuda --country TGO --povertyline 2.15 --auxpath /data/eop/compiled_country_data/auxiliary_data/auxiliary_data_20260107.csv --year 2017 
sleep 1
/home/selker/.conda/envs/dry_run/bin/python main_learn.py main --config /home/selker/eop/eop/run_togo_simulations/simulations_20260318/learn/configs/TGO_alpha_earth_and_survey_satellite_sample/oracle_gap.yaml --trainpath /data/eop/country_data/TGO/cleaned_for_nontrad_experiments/alpha_earth_and_survey_satellite_sample/train.parquet --testpath /data/eop/country_data/TGO/cleaned_for_nontrad_experiments/alpha_earth_and_survey_satellite_sample/test.parquet --summarypath /data/eop/country_data/TGO/cleaned_for_nontrad_experiments/alpha_earth_and_survey_satellite_sample/summary.parquet --device cuda --country TGO --povertyline 2.15 --auxpath /data/eop/compiled_country_data/auxiliary_data/auxiliary_data_20260107.csv --year 2017 
sleep 1
/home/selker/.conda/envs/dry_run/bin/python main_learn.py main --config /home/selker/eop/eop/run_togo_simulations/simulations_20260318/learn/configs/TGO_alpha_earth_and_survey_satellite_sample/ubi.yaml --trainpath /data/eop/country_data/TGO/cleaned_for_nontrad_experiments/alpha_earth_and_survey_satellite_sample/train.parquet --testpath /data/eop/country_data/TGO/cleaned_for_nontrad_experiments/alpha_earth_and_survey_satellite_sample/test.parquet --summarypath /data/eop/country_data/TGO/cleaned_for_nontrad_experiments/alpha_earth_and_survey_satellite_sample/summary.parquet --device cuda --country TGO --povertyline 2.15 --auxpath /data/eop/compiled_country_data/auxiliary_data/auxiliary_data_20260107.csv --year 2017 
sleep 1
