data:
  geo_extrapolation: true
  gt:
    summarypath: /data/eop/country_data/TGO/cleaned/satej_features_survey_coordinates_satellite_sample/summary.parquet
    trainpath: /data/eop/country_data/TGO/cleaned/satej_features_survey_coordinates_satellite_sample/train.parquet
  outcome: consumption_per_capita_per_day
  povertyline: 2.15
  weight: headcount_adjusted_hh_wgt
  year: 2017
oracle_gap: {}
savedir: /home/selker/eop/eop/run_togo_simulations/simulations_20260128/learn/results/TGO_satej_features_survey_coordinates_satellite_sample
